version: '3.7'

volumes:
    postgres_data:
        driver: local

networks:
    todo_network:
        driver: bridge

services:
    db: 
        image: postgres:13-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        container_name: todo_postgres
        networks: 
            - todo_network
        restart: always
        volumes:
            - postgres_data:/var/lib/postgresql/postgres_data
            - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        command: -p ${POSTGRES_PORT}

    db_test: 
        image: postgres:13-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        container_name: todo_postgres_test
        networks: 
            - todo_network
        restart: always
        volumes:
            - ./scripts/init_db_test.sql:/docker-entrypoint-initdb.d/init_db_test.sql
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        command: -p ${POSTGRES_PORT}

    dev:
        image: golang:1.14-alpine
        environment:
            ENVIRONMENT: dev
        networks: 
            - todo_network
        restart: always
        volumes:
            - .:/app
        working_dir: /app
        command: >
            /bin/sh -c "
                CGO_ENABLED=0 go run main.go"
        container_name: todo_app
        ports:
            - 5050:5050
        depends_on:
            - db

    storages_test:
        image: golang:1.14-alpine
        environment:
            ENVIRONMENT: test
        networks: 
            - todo_network
        volumes:
            - .:/app
        working_dir: /app
        command: >
            /bin/sh -c "
                CGO_ENABLED=0 go test -v -count=1 -cover ./internal/storages/postgres"
        container_name: todo_app_test_postgres
        depends_on:
            - db_test
        links:
            - db_test

    usecase_test:
        image: golang:1.14-alpine
        environment:
            ENVIRONMENT: test
        networks: 
            - todo_network
        volumes:
            - .:/app
        working_dir: /app
        command: >
            /bin/sh -c "
                CGO_ENABLED=0 go test -v -count=1 -cover ./internal/usecase"
        container_name: todo_app_test_usecase
        depends_on:
            - db_test
        
    integration_test:
        image: golang:1.14-alpine
        environment:
            ENVIRONMENT: test
        networks: 
            - todo_network
        volumes:
            - .:/app
        working_dir: /app
        command: >
            /bin/sh -c "
                CGO_ENABLED=0 go test -v -count=1 -cover ./internal/transport"
        container_name: integration_test
        depends_on:
            - db_test
        